import "/components/both/get_month_name.js"
import "/components/both/isClient.js"
import "/components/both/isRodrigo.js"
import "/components/both/isServer.js"
import "/components/both/mount_calendar.js"
import "/components/both/replaceAll.js"
import "/components/both/startup.js"
import "/components/both/dataEvaluation/lib/validationTools.js"
import "/components/both/validaCPF.js"
import '/components/both/isTrue.js'
import "/components/both/isAdmin.js"
import "/components/both/uteis/datas/dateToBr.js"
import "/components/both/trimArray.js"
import "/components/both/momentBr.js"
import '/components/both/uteis/randomElements/randomNumber.js'
import '/components/both/uteis/randomElements/randomDate.js'
import '/components/both/uteis/randomElements/randomCNPJ_CPF.js'
import '/components/both/valida_data_nascimento.js'
import '/components/both/Valida_Hora.js'
import '/components/both/users.js'
import '/components/both/dataEvaluation/cnpjValidation.js'
import '/components/both/precos.js'
import '/components/both/uteis/randomElements/randomItem.js'
import '/components/both/uteis/uteis_import.js'
import '/components/both/extract_json.js'
import '/components/both/isCompany.js'