import "/components/both_imports.js"
import "/components/client/sounds.js"
import "/components/client/alertas.js"
import "/components/client/getparams.js"
import '/components/client/getRouteName.js'
import '/components/both/forms/client_form_tools.js'
import '/components/client/titulo_elemental/titulo_elemental.js'
import '/components/client/elementos/elementos_import.js'
import '/components/client/loading/loading.js'
