//Gera randomicamente um nome completo
RandomCompleteName = function(){
    //Define alguns nomes
    var names = [
        'Adriana',
        'Bruno',
        'Alberto',
        'Joao',
        'Maria',
        'Mauricio',
        'Bruna',
        'Ricardo',
        'Alexandre',
        'Alexandra',
        'Augusto',
        'Olivia',
        'Bruno',
        'Francisco',
        'Adriano',
        'Thiago',
        'Borges',
        'Thais',
        'Miguel',
        'Davi',
        'Arthur',
        'Gabriel',
        'Pedro',
        'Lucas',
        'Matheus',
        'Bernardo',
        'Rafael',
        'Guilherme',
        'Enzo',
        'Felipe',
        'Gustavo',
        'Nicolas',
        'Heitor',
        'Samuel',
        'Joao Pedro',
        'Pedro Henrique',
        'Caua',
        'Henrique',
        'Murilo',
        'Eduardo',
        'Vitor',
        'Daniel',
        'Lorenzo',
        'Vinicius',
        'Pietro',
        'João Vitor',
        'Leonardo',
        'Théo',
        'Caio',
        'Isaac',
        'Lucca',
        'João',
        'Letícia',
        'Carlos Brito',
        'Golcalvez',
        'Manoela',
        'Manoel',
        'Roberto',
        'Roberta',
        'Carolina',
        'Caroline',
        'Yasmin',
        'Jasmin',
        'Tiago',
        'Mario',
        'Hernandez',
        'Airton',
        'Will',
        'Wellington',
        'Capio',
        'Hélio',
        'Nélio',
        'Beatriz',
        'Laura',
        'Julia',
        'Ana',
        'Sofia',
        'Isabela',
        'Larissa',
        'Maria Eduarda',
        'Camila',
        'Mariana',
        'Alice',
        'Amanda',
        'Lara',
        'Valentina',
        'Leticia',
        'Luana',
        'Sophia',
        'Helena',
        'Juliana',
        'Rebeca',
        'Manuela',
        'Fernanda',
        'Giovanna',
        'Isadora',
        'Nicole',
        'Gabriela',
        'Vanessa',
        'Lorena',
        'Jessica',
        'Bianca',
        'Luiza',
        'Vitoria',
        'Rafaela',
        'Rafael',
        'Raphael',
        'Sabrina',
        'Ester',
        'Dian',
        'Maria Clara'
    ]
    //Define alguns sobrenomes
    var secondNames = [
        'Silva',
        'Souza',
        'Mendes',
        'Oliveira',
        'Queiroz',
        'Menguel',
        'Neto',
        'Poeta',
        'Mohamed',
        'Prata',
        'Glória',
        'Humberg',
        'Munhos',
        'Castanheiras',
        'Olinda',
        'Montezuma',
        'Rosa',
        'Flores',
        'Laranjeira',
        'Lima',
        'Monte Verde',
        'Força',
        'Guerra',
        'Levante',
        'Pinheiro',
        'Mantiqueira',
        'Alvaro',
        "Dias",
        "Alameda",
        "Garcês",
        'Lobos',
        'Arantes',
        'de Assunção',
        'Assumpção',
        'Barreto',
        'Santana',
        'Palhares',
        'Tavares',
        'Sales',
        'de Quadros',
        'Peixoto',
        'Ramalho',
        'Roriz',
        'Filgueira',
        'de Lins',
        'de Lara',
        'Fogaça',
        'Barroso',
        'Pedroso',
        'Moreno',
        'Galego',
        'Crespo',
        'Negrão',
        'Solimões',
        'Mendanha',
        'Ferraço',
        'Corte',
        'de Sá',
        'do Prado',
        'Porto',
        'Louzada'
    ]

    var thirdNames = [
        'Almirantes',
        'Norgato',
        'Moraes',
        'Els',
        'Hu',
        'Mangu',
        "Datena",
        'Bulhões',
        'Quaresma',
        'Resende',
        'Rezende',
        'Longuinho',
        'Espinhosa',
        'Vidal',
    ]

    var quadNames = [
        'Hu',
        'La',
        'Thu',
        "La",
        'Sahi',
        'Sola',
        'Meo',
        'Mea',
        'Hua',
        'Chala',
        'Hi'
    ]
    //Gera um nome completo baseado na combinação aleatória dos nomes anteriores
    var randomName = RandomItem(names) + " " + RandomItem(secondNames) + " " + RandomItem(thirdNames)
    //Retorna um nome randomico
    return randomName
}